### PR TITLE
Release 0.6.0

### PR DESCRIPTION
**Pull request by Thieurom**
- https://github.com/nimblehq/nimble-crypto-ios/milestone/6?closed=1

## Features
- #37
- #41
- #42
- #44
- #62

## Chore
- #59

### CODE REVIEW

**Review by nkhanh44 — APPROVED** [review]

**Review by minhnimble — APPROVED** [review]
All good to me 🚀 Just a friendly reminder that we can add this release PR to the milestone as well for tracking purpose 😁

Screenshot 2023-01-09 at 15 15 47

**Review by minhnimble — CHANGES_REQUESTED** [review]
Oh noes, it looks like to be an archive issue with `SwiftGenPlugin`, need to check and fix it for the release @Thieurom 🛠

**Comment by Thieurom** [comment]
@minhnimble @nkhanh44  It's all good now 🙏

**Review by minhnimble — APPROVED** [review]
Let's go 🚀

**Pull request merged**
