### PR TITLE
Release 0.2.0

### PR DESCRIPTION
**Pull request by Thieurom**
https://github.com/nimblehq/nimble-crypto-ios/milestone/2?closed=1

## Features
- #3
- #4
- #6
- #16

## Chores
- #24
- #29

### CODE REVIEW

**Comment by minhnimble** [comment]
It looks like we need to fix our UI tests as the CD is failed 🛠
Screenshot 2022-12-14 at 15 33 00

**Comment by nkhanh44** [comment]
The error looks like the one we have in iOS-chapter [thread](https://nimble-co.slack.com/archives/C418DBL2W/p1670814593313569).

**Comment by Thieurom** [comment]
@minhnimble  @nkhanh44  All good now, just re-run the action!
The fail is strange because this `buildAndTest` lane is run every time a PR is open but it never fails. My best guess is normally when running UI tests the simulator will run and then launch our app. But somehow the simulator is hung at the time.

**Review by nkhanh44 — APPROVED** [review]

**Review by minhnimble — APPROVED** [review]
LGTM 🚀

**Pull request merged**
