### PR TITLE
[#36] [Chore] Update fastlane to run tests on local packages

### LINKED ISSUE #36: [Chore] Update `fastlane` to run tests on local packages
## Why

Currently, we can only run the tests on the app targets.
We need to update the existing lane or add a new one to test all the local packages that have test targets.

## Who Benefits?

- Developers who develop the module (via the local Swift package) that have unit tests.
- Code reviewers

### PR DESCRIPTION
**Pull request by nkhanh44**
- Close #36 

## What happened 👀

- Update fastlane for running tests on local packages, including: `DataTests`, `HomeTests`, `MyCoinTests`, `StyleguideTests`, and `UseCasesTests`.

## Insight 📝

- I added more targets in the `buildAndTest` lane to test all the local packages above.

## Proof Of Work 📹

_on the local:_

<details>
<summary>buildAndTestLane</summary>
<be>

</details>

_on the CI:_

<details>
<summary>buildAndTestLane</summary>
<be>

</details>

### CODE REVIEW

**Review by minhnimble — APPROVED** [review]
LGTM, nice work 🚀 Just a small suggestion that from your P.o.W, there is an update on the `firebase_app_distribution` plugin and maybe we can update it in this PR also 🙏

**Comment by Thieurom** [comment]
@nkhanh44  Nice work 👍!

I'd to suggest some small touches 🙏:
- The POW for running on the local shows that there's _0_ test since it should have 4 (as in POW on CI). Kindly update the result with the latest code 🙏 
- We still use `xcpretty` (instead of `xcbeatify`) for `xcodeBuildFormatter` in the `buildApp` lane. Please check again if there're actual errors occur. If that's not the case, update to make it consistent with other lanes.
  Screenshot 2022-12-16 at 09 37 24
- For now we don't have any UI tests, but I noticed that it takes a long time just almost do nothing on the CI. To show you an example (you can check on other runs [here](https://github.com/nimblehq/nimble-crypto-ios/actions)):
  
  Screenshot_2022-12-16_at_09_44_11

  As you can see, running zero tests on the `CryptoPricesUITests` target took ___5 minutes___ on a total of ___8 and half minutes___. It slows down our code review process and productivity. May I suggest removing the `UITests` target from the test lane (with a `TODO` mark indicating put it back when we actually add UI tests)? @minhnimble

**Comment by minhnimble** [comment]
> As you can see, running zero tests on the CryptoPricesUITests target took 5 minutes on a total of 8 and half minutes. It slows down our code review process and productivity. May I suggest removing the UITests target from the test lane (with a TODO mark indicating put it back when we actually add UI tests)? @minhnimble

@Thieurom that sounds reasonable to me, one up-vote from me 👍

**Comment by nkhanh44** [comment]
@Thieurom Thanks for the raise. I fixed all at https://github.com/nimblehq/nimble-crypto-ios/pull/52/commits/e4fed0ea1da7c25d582282c2f60f4594e4a33971.

I tested `buildAdhocStaging` lane with `xcbeautify`, it works like a charm without any issues :D.
Screenshot 2022-12-16 at 14 47 24

**Comment by nkhanh44** [comment]
> there is an update on the `firebase_app_distribution` plugin and maybe we can update it in this PR also

@minhnimble Sorry I don't get what I should update `firebase_app_distribution` plugin 🙈. Can you help me to point it out, so I can fix it here 🙏 ?

**Comment by minhnimble** [comment]
> @minhnimble Sorry I don't get what I should update `firebase_app_distribution` plugin 🙈. Can you help me to point it out, so I can fix it here 🙏 ?

Ah `firebase_app_distribution` is part of the Fastlane's gems in `Pluginfile`, so to update it you can simply run `fastlane update_plugins` in the terminal. 🚀 

For more information about Fastlane plugins, you can take a look at the below link also. Hope it helps 😁
https://docs.fastlane.tools/plugins/using-plugins/

**Comment by nkhanh44** [comment]
@minhnimble My bad 🙈, I don't know why I just ignored the message `Just a small optional suggestion from your P.o.W` from your comment, so I was confused why you asked to update that 😅 . Thank you 💯. I updated it at https://github.com/nimblehq/nimble-crypto-ios/pull/52/commits/bed9d71709296dabb57bd16dffe009c0d02f5a50.

**Review by Thieurom — APPROVED** [review]
💯 🚀

**Pull request merged**
